language: csharp
dist: xenial
mono: none
dotnet: 2.2.104

env:
  - CONFIGURATION=Release

os:
  - linux
  - osx
install:
- dotnet restore

script:
- cd "src/C++ Library"
- mkdir build
- cd build
- cmake --version
- cmake ..
- cmake --build . --target --config ${CONFIGURATION}
- cd
- cd build/JorTurFer/Workshop_RiojaDotNet
- dotnet build --configuration $CONFIGURATION
- cd src
- cd C*
- cd build
- cd 
- cd build/JorTurFer/Workshop_RiojaDotNet
- cp -a "src/C++ Library/build/." "test/NativeMehotdsTests/bin/${CONFIGURATION}/netcoreapp2.1/"
- dotnet test

-notifications:
-  email: false

