language: csharp
dist: xenial
mono: none
dotnet: 2.2.104

addons:
  sonarcloud:
    organization: "jorturfer-github"   
os:
  - linux
  - osx
install:
- dotnet restore
script:
- dotnet build
- dotnet test test/MathTests/MathTests.csproj
- sonar-scanner
-notifications:
-  email: false