version: '{build}'

install:
    # Git clone happens between init and install
  - cmd: git submodule update --init --recursive

clone_folder: c:\projects\cpp_linq_Examples
image:
  - Visual Studio 2019
  - Visual Studio 2017
  - Visual Studio 2015
  - Visual Studio 2013
configuration:
- Debug
- Release

platform:
- x64
environment:
  MSVC_DEFAULT_OPTIONS: ON
  matrix:
  - arch: Win64
matrix:
  fast_finish: true

# skip unsupported combinations
init:
- echo %platform%
- set arch=%platform%
- if "%platform%" == "Any CPU" (set arch="x64")
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 16 2019" )
- echo cmake . -G %generator% -A %arch%

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -G %generator% -A %arch%
build:
  project: c:\projects\cpp_linq_Examples\build\cpplinq_examples.sln
  verbosity: minimal
  parallel: true
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - examples/
    - cmake/
