version: 1.0.{build}

os:
  - Visual Studio 2017
  - Visual Studio 2019
  - Ubuntu
  
configuration:
- Release

before_build:
- cmd: nuget restore

build:
  project: Ejemplo NetCore.sln
  verbosity: minimal
  
only_commits:
  files:
    - appveyor.yml
    - src/
    - test/